### ISSUE TITLE
Library Loader required?

### ISSUE THREAD

**Issue by markusstephanides** [JunaMeinhold/HexaEngine.ImGui#1]
Hi! Im trying to build my project which uses this (awesome and very ergonomic!) binding lib. It works using normal .NET compilation, but I also need to use Native AOT. There the application crashes when loading the  ImGui (+extension) libs through the LibraryLoader class.

My question is, is it even necessary nowadays to load in the library manually?

I'm also using other libraries with native bindings which also don't require that (I guess because the dll name is specified at the function attributes anyways.

If that is not an option you, would it be fine to switch GetNativeAssemblyPath by System.AppContext.BaseDirectory? (its suggested by the .NET AOT Compiler)

`ILC : warning IL3000: HexaEngine.ImGuiNET.LibraryLoader.<LoadLocalLibrary>g__GetNativeAssemblyPath|6_2(String,String,String): 'System.Reflection.Assembly.Location.get' always returns an empty string for assemblies embedded  
in a single-file app. If the path to the app directory is needed, consider calling 'System.AppContext.BaseDirectory'`

EDIT: Can confirm it works without library loader which makes it wor with NativeAOT!
Thanks!

**Comment by JunaMeinhold** [comment]
Hi, the LibraryLoader is required for cross-platform capability (.dll, .so, .dylib). I already fixed this issue in a local build, but forgot to push the code and publish it on Nuget. I will release the package later today.

**Comment by JunaMeinhold** [comment]
And done, I uploaded the corrected version and updated to the latest imgui version. I tested aot compilation and it works with the sample project.
